import type { ChunkRecord, DocumentRecord } from "./types";

export const DOCUMENTS: DocumentRecord[] = [
  {
    id: "doc_lm042",
    title: "Last Mile Handling SOP v3.2",
    sourceType: "sop",
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    version: "3.2",
    updatedAt: "2026-06-12",
    summary: "Hub intake, damaged parcels, OTP delivery, and exception codes.",
  },
  {
    id: "doc_drv011",
    title: "Driver Onboarding and KYC SOP",
    sourceType: "sop",
    department: "logistics",
    allowedRoles: ["field_engineer", "knowledge_admin"],
    accessLevel: "role_restricted",
    language: "en",
    version: "1.4",
    updatedAt: "2026-05-03",
    summary: "Required KYC, vehicle papers, and first-week ride-along rules.",
  },
  {
    id: "doc_pay008",
    title: "COD and Payment Settlement Policy",
    sourceType: "policy",
    department: "payments",
    allowedRoles: ["support_agent", "knowledge_admin", "executive"],
    accessLevel: "department",
    language: "en",
    version: "2.1",
    updatedAt: "2026-07-01",
    summary: "Cash-on-delivery collection, deposit windows, and dispute holds.",
  },
  {
    id: "doc_sec001",
    title: "Security Incident Response Policy",
    sourceType: "policy",
    department: "security",
    allowedRoles: ["security_admin", "knowledge_admin"],
    accessLevel: "confidential",
    language: "en",
    version: "4.0",
    updatedAt: "2026-04-18",
    summary: "Severity classes, containment, and disclosure for security events.",
  },
  {
    id: "doc_sup003",
    title: "Customer Escalation Playbook",
    sourceType: "playbook",
    department: "support",
    allowedRoles: ["support_agent", "field_engineer", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    version: "1.8",
    updatedAt: "2026-06-28",
    summary: "P1–P3 tickets, refunds, and when to page ops.",
  },
  {
    id: "doc_hub019",
    title: "Hub Safety and PPE SOP",
    sourceType: "sop",
    department: "logistics",
    allowedRoles: ["field_engineer", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    version: "2.0",
    updatedAt: "2026-03-09",
    summary: "PPE, forklift lanes, and heat-wave rest rules.",
  },
  {
    id: "doc_mob004",
    title: "Mobile Crash and App Incident Runbook",
    sourceType: "runbook",
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    version: "1.3",
    updatedAt: "2026-07-20",
    summary: "Crashlytics spikes, offline queue, and driver-app rollback.",
  },
  {
    id: "doc_dat002",
    title: "Data Classification and Access Policy",
    sourceType: "policy",
    department: "security",
    allowedRoles: ["security_admin", "knowledge_admin"],
    accessLevel: "confidential",
    language: "en",
    version: "3.1",
    updatedAt: "2026-02-14",
    summary: "Public, internal, restricted, confidential labels and handling.",
  },
  {
    id: "doc_sla007",
    title: "Last-Mile SLA and Rate Card",
    sourceType: "sla",
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "executive", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    version: "2026.Q3",
    updatedAt: "2026-07-01",
    summary: "City-tier SLAs, failed-attempt fees, and COD surcharge.",
  },
  {
    id: "doc_lmhi",
    title: "Damage Parcel Handling — Field Note (EN/HI)",
    sourceType: "sop",
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "knowledge_admin"],
    accessLevel: "internal",
    language: "en-hi",
    version: "1.1",
    updatedAt: "2026-06-15",
    summary: "Bilingual field note for damaged and refused parcels at hub.",
  },
];

export const CHUNKS: ChunkRecord[] = [
  {
    id: "chk_lm042_01",
    documentId: "doc_lm042",
    page: 3,
    section: "Hub intake",
    headingPath: ["Last Mile Handling SOP", "Hub intake", "Scan sequence"],
    chunkIndex: 0,
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    hasTable: false,
    content:
      "Every inbound bag must be scanned at the dock door before it enters the sort belt. Use the inbound gun on mode HUB-IN. If a bag seal is broken, do not open it on the belt. Move it to Exception Cage A, photograph the seal, and raise ticket type BAG-SEAL with the bag ID. Maximum dock dwell before first scan is 12 minutes during peak (18:00–22:00 IST).",
  },
  {
    id: "chk_lm042_02",
    documentId: "doc_lm042",
    page: 12,
    section: "Damaged packages",
    headingPath: ["Last Mile Handling SOP", "Exceptions", "Damaged packages"],
    chunkIndex: 1,
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    hasTable: false,
    content:
      "SOP-LM-042 damaged package rule: if a carton is crushed, wet, or leaking, do not attempt last-mile delivery. Tag the shipment DAMAGED-HOLD in the driver app, take three photos (outer, label, inner if already open), and return it to the originating hub on the same night trip. Never re-tape and send. Customer comms are owned by Support using template DMG-01. If contents are hazardous or leaking liquid, isolate in the yellow spill tray and page Hub Safety.",
  },
  {
    id: "chk_lm042_03",
    documentId: "doc_lm042",
    page: 14,
    section: "OTP delivery",
    headingPath: ["Last Mile Handling SOP", "Delivery", "OTP"],
    chunkIndex: 2,
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    hasTable: false,
    content:
      "High-value shipments (declared value ≥ ₹5,000) and all electronics require a 4-digit OTP shown on the consignee phone. Drivers must not accept a screenshot. If OTP fails three times, mark ATTEMPT-OTP-FAIL and do not leave the parcel with a neighbour or guard. PIN-code exceptions listed in Annex C (gated societies with registered reception) may use reception OTP only when the society is flagged RECEPTION-OK in the app.",
  },
  {
    id: "chk_lm042_04",
    documentId: "doc_lm042",
    page: 18,
    section: "Failed attempts",
    headingPath: ["Last Mile Handling SOP", "Delivery", "Failed attempts"],
    chunkIndex: 3,
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    hasTable: true,
    content:
      "Attempt codes: ND-1 customer not available, ND-2 address incomplete, ND-3 refused, ND-4 area not accessible, ND-5 OTP fail. After two failed attempts on consecutive days, hold at hub for 48 hours then auto-RTO. Do not create a third attempt unless Support raises a REATTEMPT ticket. COD parcels refused at door are treated as ND-3 and cash must never be collected.",
  },
  {
    id: "chk_drv011_01",
    documentId: "doc_drv011",
    page: 2,
    section: "KYC pack",
    headingPath: ["Driver Onboarding", "KYC", "Required documents"],
    chunkIndex: 0,
    department: "logistics",
    allowedRoles: ["field_engineer", "knowledge_admin"],
    accessLevel: "role_restricted",
    language: "en",
    hasTable: false,
    content:
      "A new last-mile partner cannot be activated until the KYC pack is complete: Aadhaar (masked last 4 in the app), PAN, live selfie match, driving licence valid for at least 90 days, and RC of the vehicle that will run the beat. Two-wheeler partners also need a PUC not older than 6 months. Reject photocopies that are cropped or laminated with glare. City leads approve KYC within one business day.",
  },
  {
    id: "chk_drv011_02",
    documentId: "doc_drv011",
    page: 6,
    section: "Ride-along",
    headingPath: ["Driver Onboarding", "First week", "Ride-along"],
    chunkIndex: 1,
    department: "logistics",
    allowedRoles: ["field_engineer", "knowledge_admin"],
    accessLevel: "role_restricted",
    language: "en",
    hasTable: false,
    content:
      "Every new partner completes one supervised ride-along with a trainer or city lead before solo dispatch. Minimum 18 drops covering OTP, COD, and one exception. Trainer scores the card in the app. Score below 70 requires a second ride-along. Partners must not share login OTPs or run dual accounts. Dual-account is a P1 integrity event — escalate to Security, do not just deactivate in the field.",
  },
  {
    id: "chk_pay008_01",
    documentId: "doc_pay008",
    page: 4,
    section: "COD deposit",
    headingPath: ["COD Settlement", "Collection", "Deposit window"],
    chunkIndex: 0,
    department: "payments",
    allowedRoles: ["support_agent", "knowledge_admin", "executive"],
    accessLevel: "department",
    language: "en",
    hasTable: false,
    content:
      "Cash collected on a delivery day must be deposited at the designated hub locker or partner bank drop by 11:00 IST the next calendar day, including Sundays for metro hubs. Variance above ₹200 is a settlement exception and freezes the partner payout for that cycle. Do not instruct a driver to hold cash overnight beyond this window. UPI-on-delivery is preferred and closes the COD bag automatically.",
  },
  {
    id: "chk_pay008_02",
    documentId: "doc_pay008",
    page: 9,
    section: "Disputes",
    headingPath: ["COD Settlement", "Disputes", "Customer claims"],
    chunkIndex: 1,
    department: "payments",
    allowedRoles: ["support_agent", "knowledge_admin", "executive"],
    accessLevel: "department",
    language: "en",
    hasTable: false,
    content:
      "If a customer claims they paid cash but the app shows unpaid, Support must not reverse settlement from the partner bag without a signed proof photo or locker tape. Raise PAY-DISPUTE. Finance reviews within 3 working days. Refunds to the customer, when approved, are issued to the original UPI or as a wallet credit — never as cash from the hub till. Settlement timeline for clean COD bags is T+2 banking days.",
  },
  {
    id: "chk_sec001_01",
    documentId: "doc_sec001",
    page: 2,
    section: "Severity",
    headingPath: ["Incident Response", "Classify", "Severity"],
    chunkIndex: 0,
    department: "security",
    allowedRoles: ["security_admin", "knowledge_admin"],
    accessLevel: "confidential",
    language: "en",
    hasTable: true,
    content:
      "SEV-1: active account takeover, payment key leak, or ransomware on hub systems. Page #sec-oncall and isolate the service within 15 minutes. SEV-2: suspected token reuse or scanner finding with public exploit. SEV-3: informational scanner noise. Do not discuss SEV-1 details in public Slack. Disclosure to customers is owned by Security, never Support or Field.",
  },
  {
    id: "chk_sec001_02",
    documentId: "doc_sec001",
    page: 7,
    section: "Auth incidents",
    headingPath: ["Incident Response", "Playbooks", "Auth"],
    chunkIndex: 1,
    department: "security",
    allowedRoles: ["security_admin", "knowledge_admin"],
    accessLevel: "confidential",
    language: "en",
    hasTable: false,
    content:
      "If a high-severity vuln is tied to auth PRs, rotate the affected client secrets, invalidate refresh tokens issued in the last 24 hours, and pull the related GitHub PR numbers into the IR ticket. HubSpot customer impact is listed only on the confidential IR channel. Field engineers are not given exploit details or secret values. After containment, write the 72-hour postmortem in the security Confluence space.",
  },
  {
    id: "chk_sup003_01",
    documentId: "doc_sup003",
    page: 3,
    section: "Priority",
    headingPath: ["Escalation Playbook", "Triage", "Priority"],
    chunkIndex: 0,
    department: "support",
    allowedRoles: ["support_agent", "field_engineer", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    hasTable: true,
    content:
      "P1: perishable or wedding-date shipment missed, or COD amount ≥ ₹25,000 stuck. Page city ops and call the customer within 15 minutes. P2: SLA breach likely today, damaged in transit, or wrong pin. P3: general tracking questions. Do not promise a refund on first contact. Refunds require Finance code RFND-OK except for the auto-approved ₹200 goodwill cap.",
  },
  {
    id: "chk_sup003_02",
    documentId: "doc_sup003",
    page: 8,
    section: "When to page field",
    headingPath: ["Escalation Playbook", "Field", "Page rules"],
    chunkIndex: 1,
    department: "support",
    allowedRoles: ["support_agent", "field_engineer", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    hasTable: false,
    content:
      "Page a field engineer only when the parcel is physically at a hub or on a live beat and the customer is waiting the same day. Do not page field for app login issues or KYC status — those go to the driver desk. If the driver reports a crash loop, attach the runbook RUN-MOB-004 and create a mobile incident, then notify the on-call mobile engineer.",
  },
  {
    id: "chk_hub019_01",
    documentId: "doc_hub019",
    page: 4,
    section: "PPE",
    headingPath: ["Hub Safety", "PPE", "Required kit"],
    chunkIndex: 0,
    department: "logistics",
    allowedRoles: ["field_engineer", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    hasTable: false,
    content:
      "Required PPE on the sort floor: closed safety shoes, high-vis vest, and cut-resistant gloves when breaking bags. Headphones are banned in forklift lanes. Heat-wave rule (IMD red or orange for the city): 10-minute rest every 50 minutes of floor work, oral rehydration at the water station, and no solo loft work after 13:00. Report near-misses in the safety form the same shift.",
  },
  {
    id: "chk_mob004_01",
    documentId: "doc_mob004",
    page: 2,
    section: "Crash spike",
    headingPath: ["Mobile Runbook", "Triage", "Crashlytics spike"],
    chunkIndex: 0,
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    hasTable: false,
    content:
      "A crash spike is defined as crash-free sessions dropping below 97% in 30 minutes or more than 200 events of the same fingerprint. Field workaround: force-stop the driver app, clear cache only (not data), and stay on the last known-good build listed on the status pin. Do not ask drivers to uninstall if they have an offline queue — that drops undelivered scans. If the queue is stuck, use the Export Queue action and upload the .json to the incident ticket.",
  },
  {
    id: "chk_mob004_02",
    documentId: "doc_mob004",
    page: 5,
    section: "Rollback",
    headingPath: ["Mobile Runbook", "Release", "Rollback"],
    chunkIndex: 1,
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    hasTable: false,
    content:
      "Mobile on-call may halt a staged rollout at 5% if checkout or scan success falls 3 points. Rollback is a store-listing previous build plus remote-config kill switch SCAN_V2. Field engineers should not sideload APKs. Communicate to drivers via the in-app banner, not WhatsApp forwards. After rollback, Support uses script MOB-RB to answer inbound calls.",
  },
  {
    id: "chk_dat002_01",
    documentId: "doc_dat002",
    page: 3,
    section: "Labels",
    headingPath: ["Data Classification", "Labels", "Handling"],
    chunkIndex: 0,
    department: "security",
    allowedRoles: ["security_admin", "knowledge_admin"],
    accessLevel: "confidential",
    language: "en",
    hasTable: true,
    content:
      "Confidential: KYC images, full Aadhaar, payment tokens, incident details, and customer phone dumps. Restricted: beat-level COD totals, partner bank accounts. Internal: SOPs and SLAs. Public: tracking FAQ. Confidential files must not be pasted into ChatGPT or personal drives. Field staff see only the last four of Aadhaar and never raw token values. Access reviews run quarterly for Security and Knowledge Admin roles.",
  },
  {
    id: "chk_sla007_01",
    documentId: "doc_sla007",
    page: 1,
    section: "SLA matrix",
    headingPath: ["SLA and Rate Card", "Delivery", "City tiers"],
    chunkIndex: 0,
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "executive", "knowledge_admin"],
    accessLevel: "internal",
    language: "en",
    hasTable: true,
    content:
      "Metro (Bengaluru, Mumbai, Delhi-NCR, Hyderabad, Chennai, Pune, Kolkata, Ahmedabad): 24-hour last-mile after hub-in, 95% on-time target. Tier-2: 36 hours, 92% target. Tier-3: 48 hours, 90% target. Failed-attempt fee is billed to the shipper after the second ND, not to the consignee. COD surcharge is 1.8% with a ₹18 floor. Wedding and perishable SKUs use the Metro clock even in Tier-2 if tagged PRIORITY-DATE.",
  },
  {
    id: "chk_lmhi_01",
    documentId: "doc_lmhi",
    page: 1,
    section: "Field note",
    headingPath: ["Damage Field Note", "Hub", "Damaged / refused"],
    chunkIndex: 0,
    department: "logistics",
    allowedRoles: ["field_engineer", "support_agent", "knowledge_admin"],
    accessLevel: "internal",
    language: "en-hi",
    hasTable: false,
    content:
      "Damaged parcel (डैमेज पार्सल): delivery मत करो. App में DAMAGED-HOLD टैग करो, तीन फोटो लो, और उसी रात trip पर hub वापस भेजो. Re-tape करके consignee को देना मना है. Refused COD (ग्राहक ने मना किया): ND-3, नकद मत लो. अगर पार्सल से liquid लीक हो रहा है तो yellow spill tray में रखो और Hub Safety को page करो. Customer message Support भेजेगा — field team खुद WhatsApp पर apology न लिखे.",
  },
];

export const DOC_BY_ID = Object.fromEntries(DOCUMENTS.map((d) => [d.id, d]));

export const SUGGESTED_QUERIES: { label: string; query: string; hint: string }[] = [
  {
    label: "Damaged parcel",
    query: "What is the SOP for handling a damaged package at the last-mile hub?",
    hint: "Open to field",
  },
  {
    label: "OTP delivery",
    query: "When is OTP required for delivery and what if it fails three times?",
    hint: "Open to field",
  },
  {
    label: "COD deposit",
    query: "What is the COD cash deposit timeline and when does payout freeze?",
    hint: "Payments role",
  },
  {
    label: "Driver KYC",
    query: "Which documents are required to activate a new last-mile driver?",
    hint: "Field only",
  },
  {
    label: "Auth incident",
    query: "How do we handle a high-severity auth vulnerability and which customers are affected?",
    hint: "Security only",
  },
  {
    label: "Crash spike",
    query: "Driver app crash spike — what should field do without losing the offline queue?",
    hint: "Open to field",
  },
];
